//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdemAcount
    {
        public System.Guid idemGUID { get; set; }
        public string dbLogin { get; set; }
        public string dbPass { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    }
}
